# common grammatical particals
之
也
乎
矣
焉
哉
邪
耳
已
而
則
以
且
雖
若
如
猶
亦
故
乃
夫
我
吾
汝
其
此
彼
是
有
無
為
爲
曰
謂
不
非
所
者
於
豈
然
得
能
可
將
及
皆
未
與
弗

# numbers
一
二
三
四
五
六
七
八
九
十
兩
二十
二十五
三十三
四十
五十
七十

# time-words
今

# not useful / mostly empty
在
惟
必
自
又
何
